"""Install, update, and uninstall package templates for supported AI agents."""

from __future__ import annotations

import json
import shutil
from dataclasses import dataclass, field
from hashlib import sha256
from importlib import resources
from pathlib import Path
from typing import Iterable, NamedTuple

from . import __version__
from .validation import GENERATED_MARKER, SKILL_NAME


MANIFEST_NAME = ".sfao-install.json"
MARKER_MD = f"<!-- {GENERATED_MARKER} -->"
MARKER_COMMENT = f"# {GENERATED_MARKER}"
SUPPORTED_PLATFORMS = {"codex", "claude", "copilot", "all"}


@dataclass
class InstallReport:
    installed: list[str] = field(default_factory=list)
    updated: list[str] = field(default_factory=list)
    removed: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)
    stale: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)
    directories_kept: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.errors

    def to_dict(self) -> dict[str, list[str] | bool]:
        return {
            "ok": self.ok,
            "installed": self.installed,
            "updated": self.updated,
            "removed": self.removed,
            "skipped": self.skipped,
            "stale": self.stale,
            "warnings": self.warnings,
            "errors": self.errors,
            "directories_kept": self.directories_kept,
        }


class TemplateTarget(NamedTuple):
    source: object
    target: Path


def template_root():
    return resources.files("salesforce_agent_optimizer").joinpath("templates")


def install(
    destination: Path,
    project: bool = False,
    platform: str = "all",
) -> InstallReport:
    destination = destination.resolve()
    report = InstallReport()
    selected = expand_platforms(platform)
    root = template_root()
    manifest = load_manifest(destination)
    for target in template_targets(root, destination, project, selected, report):
        copy_template_file(target.source, target.target, report, allow_create=True, manifest=manifest)
    write_manifest(destination, selected, project, report)
    return report


def update(
    destination: Path,
    project: bool = False,
    platform: str = "all",
) -> InstallReport:
    """Update only generated files for the selected platforms."""
    destination = destination.resolve()
    report = InstallReport()
    selected = expand_platforms(platform)
    root = template_root()
    manifest = load_manifest(destination)
    for target in template_targets(root, destination, project, selected, report):
        if not target.target.exists():
            report.stale.append(display_path(target.target))
            continue
        if user_edited_generated(target.target, manifest):
            relative = display_path(target.target)
            report.skipped.append(relative)
            report.warnings.append(f"Skipped generated file with local edits: {relative}")
            continue
        copy_template_file(target.source, target.target, report, allow_create=False, manifest=manifest)
    write_manifest(destination, selected, project, report)
    return report


def uninstall(
    destination: Path,
    project: bool = False,
    platform: str = "all",
    yes: bool = False,
) -> InstallReport:
    """Remove generated files for the selected platforms without touching user-owned files."""
    destination = destination.resolve()
    report = InstallReport()
    selected = expand_platforms(platform)
    if not yes:
        print(
            "This removes only files generated by salesforce-agent-optimizer. "
            "Type 'yes' to continue: ",
            end="",
        )
        if input().strip().lower() != "yes":
            report.errors.append("Uninstall cancelled by user.")
            return report
    root = template_root()
    manifest = load_manifest(destination)
    targets = template_targets(root, destination, project, selected, report)
    for target in targets:
        remove_generated_file(target.target, manifest, report)
    remove_manifest_if_safe(destination, report)
    clean_empty_generated_dirs(destination, selected, project, report)
    return report


def expand_platforms(platform: str) -> list[str]:
    normalized = platform.lower()
    if normalized not in SUPPORTED_PLATFORMS:
        raise ValueError(f"Unsupported platform: {platform}")
    if normalized == "all":
        return ["codex", "claude", "copilot"]
    return [normalized]


def template_targets(root, destination: Path, project: bool, platforms: Iterable[str], report: InstallReport) -> list[TemplateTarget]:
    targets: list[TemplateTarget] = []
    for item in platforms:
        if item == "codex":
            base = destination / ".agents" / "skills" / SKILL_NAME
            targets.append(TemplateTarget(root / "codex" / "SKILL.md", base / "SKILL.md"))
            targets.append(
                TemplateTarget(root / "agents" / "openai.yaml", base / "agents" / "openai.yaml")
            )
            targets.extend(tree_targets(root / "references", base / "references"))
            targets.extend(tree_targets(root / "scripts", base / "scripts"))
        elif item == "claude":
            base = destination / ".claude" / "skills" / SKILL_NAME
            targets.append(TemplateTarget(root / "claude" / "SKILL.md", base / "SKILL.md"))
            targets.extend(tree_targets(root / "references", base / "references"))
            targets.extend(tree_targets(root / "scripts", base / "scripts"))
        elif item == "copilot":
            if not project:
                report.warnings.append("GitHub Copilot instructions are repository-scoped; rerun with --project.")
                continue
            targets.append(TemplateTarget(root / "AGENTS.md", destination / "AGENTS.md"))
            targets.append(
                TemplateTarget(
                    root / "github" / "copilot-instructions.md",
                    destination / ".github" / "copilot-instructions.md",
                )
            )
            targets.append(
                TemplateTarget(
                    root / "github" / "instructions" / "salesforce-agent-optimizer.instructions.md",
                    destination
                    / ".github"
                    / "instructions"
                    / "salesforce-agent-optimizer.instructions.md",
                )
            )
    return targets


def tree_targets(source, target: Path) -> list[TemplateTarget]:
    targets: list[TemplateTarget] = []
    for child in source.iterdir():
        if child.name == "__pycache__" or child.name.endswith(".pyc"):
            continue
        child_target = target / child.name
        if child.is_dir():
            targets.extend(tree_targets(child, child_target))
        else:
            targets.append(TemplateTarget(child, child_target))
    return targets


def copy_template_file(
    source,
    target: Path,
    report: InstallReport,
    allow_create: bool,
    manifest: dict[str, object] | None = None,
) -> None:
    content = source.read_bytes()
    generated = generated_bytes(content, target.suffix.lower())
    existed = target.exists()
    if not existed and not allow_create:
        report.stale.append(display_path(target))
        return
    if existed and not is_managed_file(target) and not is_tracked_unchanged(target, manifest or {}):
        relative = display_path(target)
        report.skipped.append(relative)
        report.warnings.append(f"Skipped existing non-generated file: {relative}")
        return
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(generated)
    if existed:
        report.updated.append(display_path(target))
    else:
        report.installed.append(display_path(target))


def generated_bytes(content: bytes, suffix: str) -> bytes:
    try:
        text = content.decode("utf-8")
    except UnicodeDecodeError:
        return content
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    marked = add_marker(text, suffix)
    return marked.encode("utf-8")


def add_marker(text: str, suffix: str) -> str:
    if GENERATED_MARKER in text:
        return ensure_final_newline(text)
    marker = marker_for_suffix(suffix)
    if not marker:
        return ensure_final_newline(text)
    if suffix == ".md" and text.startswith("---\n"):
        lines = text.splitlines()
        try:
            end = lines[1:].index("---") + 1
        except ValueError:
            return ensure_final_newline(f"{marker}\n{text}")
        lines.insert(end + 1, "")
        lines.insert(end + 2, marker)
        return ensure_final_newline("\n".join(lines))
    if suffix == ".py" and text.startswith("#!"):
        first, _, rest = text.partition("\n")
        return ensure_final_newline(f"{first}\n{marker}\n{rest}")
    return ensure_final_newline(f"{marker}\n{text}")


def marker_for_suffix(suffix: str) -> str:
    if suffix == ".md":
        return MARKER_MD
    if suffix in {".yaml", ".yml", ".py", ".toml", ".txt"}:
        return MARKER_COMMENT
    return ""


def ensure_final_newline(text: str) -> str:
    return text if text.endswith("\n") else text + "\n"


def is_managed_file(path: Path) -> bool:
    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return False
    return GENERATED_MARKER in text


def managed_hash(path: Path) -> str | None:
    try:
        return sha256(path.read_bytes()).hexdigest()
    except OSError:
        return None


def load_manifest(destination: Path) -> dict[str, object]:
    path = destination / MANIFEST_NAME
    if not path.exists():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return payload if isinstance(payload, dict) else {}


def manifest_hashes(manifest: dict[str, object]) -> dict[str, str]:
    files = manifest.get("files", {})
    if not isinstance(files, dict):
        return {}
    result: dict[str, str] = {}
    for path, payload in files.items():
        if isinstance(payload, dict) and isinstance(payload.get("sha256"), str):
            result[str(path)] = str(payload["sha256"])
    return result


def user_edited_generated(path: Path, manifest: dict[str, object]) -> bool:
    previous = manifest_hashes(manifest).get(display_path(path))
    current = managed_hash(path)
    return previous is not None and current is not None and previous != current


def is_tracked_unchanged(path: Path, manifest: dict[str, object]) -> bool:
    previous = manifest_hashes(manifest).get(display_path(path))
    current = managed_hash(path)
    return previous is not None and current is not None and previous == current


def remove_generated_file(path: Path, manifest: dict[str, object], report: InstallReport) -> None:
    if not path.exists():
        report.stale.append(display_path(path))
        return
    relative = display_path(path)
    tracked_hash = manifest_hashes(manifest).get(relative)
    current_hash = managed_hash(path)
    managed = is_managed_file(path) or (tracked_hash is not None and tracked_hash == current_hash)
    if not managed:
        report.skipped.append(relative)
        report.warnings.append(f"Skipped non-generated file: {relative}")
        return
    if tracked_hash is not None and current_hash is not None and tracked_hash != current_hash:
        report.skipped.append(relative)
        report.warnings.append(f"Skipped generated file with local edits: {relative}")
        return
    path.unlink()
    report.removed.append(relative)


def remove_manifest_if_safe(destination: Path, report: InstallReport) -> None:
    manifest = destination / MANIFEST_NAME
    if manifest.exists():
        manifest.unlink()
        report.removed.append(display_path(manifest))


def clean_empty_generated_dirs(
    destination: Path,
    platforms: Iterable[str],
    project: bool,
    report: InstallReport,
) -> None:
    protected = {destination, destination / ".agents", destination / ".claude", destination / ".github"}
    candidates: list[Path] = []
    selected = set(platforms)
    if "codex" in selected:
        candidates.append(destination / ".agents" / "skills" / SKILL_NAME)
    if "claude" in selected:
        candidates.append(destination / ".claude" / "skills" / SKILL_NAME)
    if "copilot" in selected and project:
        candidates.append(destination / ".github" / "instructions")
    for root in candidates:
        remove_empty_dirs_up_to(root, protected, report)


def remove_empty_dirs_up_to(path: Path, protected: set[Path], report: InstallReport) -> None:
    if path.exists():
        for child in sorted((item for item in path.rglob("*") if item.is_dir()), reverse=True):
            if child in protected:
                continue
            try:
                child.rmdir()
            except OSError:
                report.directories_kept.append(display_path(child))
    current = path
    while current.exists() and current not in protected:
        try:
            current.rmdir()
        except OSError:
            report.directories_kept.append(display_path(current))
            return
        current = current.parent


def write_manifest(
    destination: Path,
    platforms: Iterable[str],
    project: bool,
    report: InstallReport,
) -> None:
    if report.errors:
        return
    touched = [*report.installed, *report.updated]
    manifest = {
        "name": SKILL_NAME,
        "version": __version__,
        "project": project,
        "platforms": list(platforms),
        "installed": report.installed,
        "updated": report.updated,
        "skipped": report.skipped,
        "files": {
            path: {"sha256": managed_hash(Path(path)) or ""}
            for path in touched
            if Path(path).exists()
        },
    }
    target = destination / MANIFEST_NAME
    target.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8", newline="\n")


def display_path(path: Path) -> str:
    return str(path).replace("\\", "/")


def user_destination() -> Path:
    return Path.home()


def project_destination() -> Path:
    return Path.cwd()


def remove_tree(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)
