"""Validation helpers for Salesforce Agent Optimizer."""

from __future__ import annotations

import json
import os
import py_compile
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

try:  # Python 3.11+
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - Python 3.10 fallback
    tomllib = None  # type: ignore[assignment]

try:
    import yaml  # type: ignore[import-untyped]
except Exception:  # pragma: no cover - optional dependency
    yaml = None


SKILL_NAME = "salesforce-agent-optimizer"
GENERATED_MARKER = "Generated by salesforce-agent-optimizer. Managed by sfao."
MAX_DESCRIPTION_LENGTH = 1024
TEXT_SUFFIXES = {".md", ".py", ".yaml", ".yml", ".json", ".toml", ".txt", ".xml"}
YAML_SUFFIXES = {".yaml", ".yml"}
REQUIRED_COMPATIBILITY = {
    "agents": {"Codex", "Claude Code", "GitHub Copilot"},
    "platforms": {"Windows", "macOS", "Linux"},
    "prerequisites": {"Python 3.10+", "Git", "Salesforce CLI"},
}
SOURCE_REQUIRED_FILES = [
    "SKILL.md",
    "VERSION",
    "CHANGELOG.md",
    "README.md",
    "SECURITY.md",
    "CONTRIBUTING.md",
    "AGENTS.md",
    "pyproject.toml",
    "agents/openai.yaml",
    ".agents/skills/salesforce-agent-optimizer/SKILL.md",
    ".claude/skills/salesforce-agent-optimizer/SKILL.md",
    ".github/copilot-instructions.md",
    ".github/instructions/salesforce-agent-optimizer.instructions.md",
    ".github/workflows/validate.yml",
    ".github/workflows/release.yml",
    "docs/publishing.md",
    "references/routing.md",
    "references/agent-instruction-spine.md",
    "scripts/sync_agent_instructions.py",
    "scripts/build_release_artifacts.py",
    "src/salesforce_agent_optimizer/__init__.py",
    "src/salesforce_agent_optimizer/cli.py",
    "src/salesforce_agent_optimizer/installer.py",
    "src/salesforce_agent_optimizer/doctor.py",
    "src/salesforce_agent_optimizer/validation.py",
    "src/salesforce_agent_optimizer/knowledge.py",
    "src/salesforce_agent_optimizer/version_context.py",
    "src/salesforce_agent_optimizer/templates/SKILL.md",
    "src/salesforce_agent_optimizer/templates/AGENTS.md",
    "src/salesforce_agent_optimizer/templates/agents/openai.yaml",
    "src/salesforce_agent_optimizer/templates/codex/SKILL.md",
    "src/salesforce_agent_optimizer/templates/claude/SKILL.md",
    "src/salesforce_agent_optimizer/templates/github/copilot-instructions.md",
    "src/salesforce_agent_optimizer/templates/github/instructions/salesforce-agent-optimizer.instructions.md",
    "evals/trigger-evals.json",
    "tests/test_packaging_cli.py",
]
INSTALL_REQUIRED_FILES = [
    ".agents/skills/salesforce-agent-optimizer/SKILL.md",
    ".agents/skills/salesforce-agent-optimizer/references/routing.md",
    ".agents/skills/salesforce-agent-optimizer/scripts/sf_agent_cli.py",
    ".agents/skills/salesforce-agent-optimizer/agents/openai.yaml",
    ".claude/skills/salesforce-agent-optimizer/SKILL.md",
    ".claude/skills/salesforce-agent-optimizer/references/routing.md",
    ".claude/skills/salesforce-agent-optimizer/scripts/sf_agent_cli.py",
    "AGENTS.md",
    ".github/copilot-instructions.md",
    ".github/instructions/salesforce-agent-optimizer.instructions.md",
]


@dataclass
class ValidationResult:
    """Collect validation messages."""

    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.errors

    def error(self, message: str) -> None:
        self.errors.append(message)

    def warn(self, message: str) -> None:
        self.warnings.append(message)

    def to_dict(self) -> dict[str, Any]:
        return {"ok": self.ok, "errors": self.errors, "warnings": self.warnings}


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def parse_frontmatter(path: Path) -> tuple[dict[str, Any], str, str]:
    text = read_text(path)
    lines = text.splitlines()
    if not lines or lines[0] != "---":
        raise ValueError(f"{path} missing opening YAML frontmatter delimiter")
    try:
        end = lines[1:].index("---") + 1
    except ValueError as exc:
        raise ValueError(f"{path} missing closing YAML frontmatter delimiter") from exc
    raw = "\n".join(lines[1:end])
    if yaml is not None:
        data = yaml.safe_load(raw) or {}
    else:
        data = parse_simple_yaml(raw)
    if not isinstance(data, dict):
        raise ValueError(f"{path} frontmatter must be a YAML mapping")
    body = "\n".join(lines[end + 1 :])
    return data, body, raw


def parse_simple_yaml(raw: str) -> dict[str, Any]:
    """Parse the small YAML subset used by this package when PyYAML is unavailable."""
    result: dict[str, Any] = {}
    section: str | None = None
    subsection: str | None = None
    for line in raw.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        indent = len(line) - len(line.lstrip(" "))
        stripped = line.strip()
        if indent == 0 and stripped.endswith(":"):
            section = stripped[:-1]
            subsection = None
            result[section] = {}
            continue
        key, _, value = stripped.partition(":")
        if indent == 0 and value.strip():
            result[key] = unquote(value.strip())
            continue
        if indent == 2 and section:
            container = result.setdefault(section, {})
            if stripped.endswith(":"):
                subsection = key
                if isinstance(container, dict):
                    container[subsection] = []
            elif value.strip() and isinstance(container, dict):
                container[key] = unquote(value.strip())
            continue
        if indent == 4 and section and subsection and stripped.startswith("- "):
            container = result.setdefault(section, {})
            if isinstance(container, dict):
                values = container.setdefault(subsection, [])
                if isinstance(values, list):
                    values.append(unquote(stripped[2:].strip()))
    return result


def unquote(value: str) -> str:
    if (value.startswith('"') and value.endswith('"')) or (
        value.startswith("'") and value.endswith("'")
    ):
        return value[1:-1]
    return value


def parse_pyproject_version(path: Path) -> str | None:
    text = read_text(path)
    if tomllib is not None:
        data = tomllib.loads(text)
        project = data.get("project", {})
        if isinstance(project, dict):
            value = project.get("version")
            return str(value) if value is not None else None
    match = re.search(r'(?m)^version\s*=\s*["\']([^"\']+)["\']', text)
    return match.group(1) if match else None


def validate_required_files(root: Path, result: ValidationResult, files: list[str]) -> None:
    for relative in files:
        if not (root / relative).exists():
            result.error(f"Missing required file: {relative}")


def validate_text_shape(root: Path, result: ValidationResult) -> None:
    ignored = {".git", ".pytest_cache", "__pycache__", "dist", "build", ".venv", "venv"}
    for path in sorted(root.rglob("*")):
        if any(part in ignored or part.endswith(".egg-info") for part in path.parts):
            continue
        if not path.is_file() or path.suffix.lower() not in TEXT_SUFFIXES | YAML_SUFFIXES:
            continue
        try:
            data = path.read_bytes()
            text = data.decode("utf-8")
        except UnicodeDecodeError as exc:
            result.error(f"File is not UTF-8: {path.relative_to(root)}: {exc}")
            continue
        if data and not data.endswith(b"\n"):
            result.error(f"Missing final newline: {path.relative_to(root)}")
        if b"\r\n" in data:
            result.error(f"CRLF newline found; expected LF: {path.relative_to(root)}")
        if len(text) > 300 and len(text.splitlines()) <= 1:
            result.error(f"File appears collapsed into one line: {path.relative_to(root)}")
        if "\\n" in text and len(text.splitlines()) <= 2 and len(text) > 300:
            result.error(
                f"File may contain escaped newlines instead of real newlines: {path.relative_to(root)}"
            )


def validate_json_files(root: Path, result: ValidationResult) -> None:
    for path in sorted(root.rglob("*.json")):
        if ".git" in path.parts or "dist" in path.parts:
            continue
        try:
            json.loads(read_text(path))
        except json.JSONDecodeError as exc:
            result.error(f"Invalid JSON {path.relative_to(root)}: {exc}")


def validate_toml_files(root: Path, result: ValidationResult) -> None:
    for path in sorted(root.rglob("*.toml")):
        if ".git" in path.parts:
            continue
        if tomllib is None:
            if parse_pyproject_version(path) is None and path.name == "pyproject.toml":
                result.error(f"Invalid TOML {path.relative_to(root)}: missing project.version")
            continue
        try:
            tomllib.loads(read_text(path))
        except Exception as exc:  # noqa: BLE001
            result.error(f"Invalid TOML {path.relative_to(root)}: {exc}")


def validate_yaml_files(root: Path, result: ValidationResult) -> None:
    for path in sorted(root.rglob("*")):
        if ".git" in path.parts or path.suffix.lower() not in YAML_SUFFIXES:
            continue
        text = read_text(path)
        if yaml is not None:
            try:
                yaml.safe_load(text)
            except Exception as exc:  # noqa: BLE001
                result.error(f"Invalid YAML {path.relative_to(root)}: {exc}")
        elif "\t" in text:
            result.error(f"Invalid YAML {path.relative_to(root)}: tab indentation is not supported")


def validate_python(root: Path, result: ValidationResult) -> None:
    for directory in ("scripts", "src", "tests"):
        base = root / directory
        if not base.exists():
            continue
        for path in sorted(base.rglob("*.py")):
            if "__pycache__" in path.parts:
                continue
            temporary = tempfile.NamedTemporaryFile(delete=False)
            temporary.close()
            try:
                py_compile.compile(str(path), cfile=temporary.name, doraise=True)
            except py_compile.PyCompileError as exc:
                result.error(f"Python compile failed for {path.relative_to(root)}: {exc.msg}")
            finally:
                try:
                    os.unlink(temporary.name)
                except FileNotFoundError:
                    pass


def validate_skill_file(
    path: Path,
    result: ValidationResult,
    expected_version: str,
    require_all_compatibility: bool = False,
) -> None:
    try:
        data, _, _ = parse_frontmatter(path)
    except ValueError as exc:
        result.error(str(exc))
        return
    label = path.name if path.name != "SKILL.md" else str(path)
    if data.get("name") != SKILL_NAME:
        result.error(f"{label} name must be {SKILL_NAME}")
    if not re.fullmatch(r"[a-z0-9-]{1,64}", str(data.get("name", ""))):
        result.error(f"{label} name must be lowercase letters, digits, and hyphens only")
    description = data.get("description")
    if not isinstance(description, str) or not description.strip():
        result.error(f"{label} description must be a non-empty string")
    elif len(description) > MAX_DESCRIPTION_LENGTH:
        result.error(f"{label} description exceeds {MAX_DESCRIPTION_LENGTH} characters")
    if data.get("license") != "MIT":
        result.error(f"{label} license must be MIT")
    metadata = data.get("metadata", {})
    if not isinstance(metadata, dict) or str(metadata.get("version")) != expected_version:
        result.error(f"{label} metadata.version must match {expected_version}")
    if require_all_compatibility:
        compatibility = data.get("compatibility", {})
        if not isinstance(compatibility, dict):
            result.error(f"{label} compatibility must be a mapping")
            return
        for key, required_values in REQUIRED_COMPATIBILITY.items():
            values = compatibility.get(key, [])
            if not isinstance(values, list):
                result.error(f"{label} compatibility.{key} must be a list")
                continue
            missing = required_values - {str(item) for item in values}
            if missing:
                result.error(f"{label} compatibility.{key} missing: {', '.join(sorted(missing))}")


def validate_version_alignment(root: Path, result: ValidationResult) -> str:
    version_path = root / "VERSION"
    version = read_text(version_path).strip() if version_path.exists() else ""
    if not version:
        result.error("VERSION is missing or empty")
        return ""
    pyproject = root / "pyproject.toml"
    if pyproject.exists():
        project_version = parse_pyproject_version(pyproject)
        if project_version != version:
            result.error("pyproject.toml project.version must match VERSION")
    changelog = root / "CHANGELOG.md"
    if changelog.exists() and version not in read_text(changelog):
        result.error("CHANGELOG.md must contain the current version entry")
    return version


def validate_openai_yaml(root: Path, result: ValidationResult, expected_version: str) -> None:
    path = root / "agents" / "openai.yaml"
    if not path.exists():
        result.error("Missing agents/openai.yaml")
        return
    text = read_text(path)
    if len(text.splitlines()) < 3:
        result.error("agents/openai.yaml must be multi-line YAML")
    if yaml is not None:
        data = yaml.safe_load(text)
        if not isinstance(data, dict) or "interface" not in data:
            result.error("agents/openai.yaml must contain an interface mapping")
        metadata = data.get("metadata", {}) if isinstance(data, dict) else {}
        if not isinstance(metadata, dict) or str(metadata.get("version")) != expected_version:
            result.error("agents/openai.yaml metadata.version must match VERSION")
    elif expected_version not in text:
        result.error("agents/openai.yaml must include current VERSION")


def validate_generated_sync(root: Path, result: ValidationResult) -> None:
    script = root / "scripts" / "sync_agent_instructions.py"
    if not script.exists():
        return
    if yaml is None:
        managed_files = [
            "AGENTS.md",
            ".agents/skills/salesforce-agent-optimizer/SKILL.md",
            ".claude/skills/salesforce-agent-optimizer/SKILL.md",
            ".github/copilot-instructions.md",
            ".github/instructions/salesforce-agent-optimizer.instructions.md",
        ]
        for relative in managed_files:
            path = root / relative
            if path.exists() and GENERATED_MARKER not in read_text(path):
                result.error(f"Managed generated file is missing marker: {relative}")
        result.warn("Strict generated-file sync check skipped because PyYAML is not installed")
        return
    completed = subprocess.run(
        [sys.executable, str(script), "--root", str(root), "--check"],
        text=True,
        encoding="utf-8",
        errors="replace",
        capture_output=True,
        check=False,
    )
    if completed.returncode != 0:
        result.error("Generated agent instruction files are stale. Run: python scripts/sync_agent_instructions.py")


def validate_trigger_evals(root: Path, result: ValidationResult) -> None:
    path = root / "evals" / "trigger-evals.json"
    if not path.exists():
        result.error("Missing evals/trigger-evals.json")
        return
    payload = json.loads(read_text(path))
    for key in ("should_trigger", "should_not_trigger"):
        items = payload.get(key)
        if not isinstance(items, list) or len(items) < 5:
            result.error(f"evals/trigger-evals.json must include at least five {key} examples")
            continue
        for index, item in enumerate(items):
            if not isinstance(item, dict) or not item.get("prompt") or not item.get("reason"):
                result.error(f"evals/trigger-evals.json {key}[{index}] must include prompt and reason")


def validate_templates(root: Path, result: ValidationResult, expected_version: str) -> None:
    template_root = root / "src" / "salesforce_agent_optimizer" / "templates"
    if not template_root.exists():
        result.error("Package templates are missing")
        return
    for path in template_root.rglob("*"):
        if path.name == "__pycache__" or path.suffix == ".pyc":
            result.error(f"Package template contains Python cache artifact: {path.relative_to(root)}")
    required = [
        "SKILL.md",
        "AGENTS.md",
        "agents/openai.yaml",
        "references/routing.md",
        "scripts/sf_agent_cli.py",
        "codex/SKILL.md",
        "claude/SKILL.md",
        "github/copilot-instructions.md",
        "github/instructions/salesforce-agent-optimizer.instructions.md",
    ]
    for relative in required:
        path = template_root / relative
        if not path.exists():
            result.error(f"Missing package template: {relative}")
    for relative in ("SKILL.md", "codex/SKILL.md", "claude/SKILL.md"):
        path = template_root / relative
        if path.exists():
            validate_skill_file(path, result, expected_version, require_all_compatibility=False)


def validate_copilot_apply_to(root: Path, result: ValidationResult) -> None:
    path = root / ".github" / "instructions" / "salesforce-agent-optimizer.instructions.md"
    if not path.exists():
        return
    try:
        data, _, _ = parse_frontmatter(path)
    except ValueError as exc:
        result.error(str(exc))
        return
    apply_to = data.get("applyTo")
    if not isinstance(apply_to, str) or "force-app" not in apply_to or "package.xml" not in apply_to:
        result.error(".github instructions file must include applyTo frontmatter for Salesforce files")


def validate_release_workflow(root: Path, result: ValidationResult) -> None:
    path = root / ".github" / "workflows" / "release.yml"
    if not path.exists():
        return
    text = read_text(path)
    required_fragments = [
        "PUBLISH_TO_PYPI",
        "pypa/gh-action-pypi-publish@release/v1",
        "python-package-distributions",
        "environment:",
        "name: pypi",
        "id-token: write",
    ]
    for fragment in required_fragments:
        if fragment not in text:
            result.error(f"release.yml missing required Trusted Publishing fragment: {fragment}")
    if "PYPI_API_TOKEN" in text or "__token__" in text:
        result.error("release.yml must not reference static PyPI credentials")


def validate_prohibited_references(root: Path, result: ValidationResult) -> None:
    skill_suffix = "sf" + "-skills"
    prohibited = ("forcedotcom/" + skill_suffix, skill_suffix)
    for path in sorted(root.rglob("*")):
        if any(part in {".git", ".pytest_cache", "__pycache__", "dist", "build"} for part in path.parts):
            continue
        if not path.is_file() or path.suffix.lower() not in TEXT_SUFFIXES | YAML_SUFFIXES:
            continue
        try:
            text = read_text(path)
        except UnicodeDecodeError:
            continue
        for phrase in prohibited:
            if phrase in text:
                result.error(f"Prohibited dependency reference found in {path.relative_to(root)}")


def validate_source_tree(root: Path) -> ValidationResult:
    root = root.resolve()
    result = ValidationResult()
    validate_required_files(root, result, SOURCE_REQUIRED_FILES)
    version = validate_version_alignment(root, result)
    if version:
        validate_skill_file(root / "SKILL.md", result, version, require_all_compatibility=True)
        validate_skill_file(
            root / ".agents" / "skills" / SKILL_NAME / "SKILL.md",
            result,
            version,
        )
        validate_skill_file(root / ".claude" / "skills" / SKILL_NAME / "SKILL.md", result, version)
        validate_openai_yaml(root, result, version)
        validate_templates(root, result, version)
    validate_yaml_files(root, result)
    validate_toml_files(root, result)
    validate_json_files(root, result)
    validate_python(root, result)
    validate_text_shape(root, result)
    validate_trigger_evals(root, result)
    validate_generated_sync(root, result)
    validate_copilot_apply_to(root, result)
    validate_release_workflow(root, result)
    validate_prohibited_references(root, result)
    return result


def validate_installation(root: Path, expected_version: str | None = None) -> ValidationResult:
    root = root.resolve()
    result = ValidationResult()
    found_any = False
    for relative in INSTALL_REQUIRED_FILES:
        path = root / relative
        if path.exists():
            found_any = True
        else:
            result.warn(f"Missing installed file: {relative}")
    if not found_any:
        result.error("No Salesforce Agent Optimizer installation files found")
        return result
    if expected_version:
        for relative in (
            ".agents/skills/salesforce-agent-optimizer/SKILL.md",
            ".claude/skills/salesforce-agent-optimizer/SKILL.md",
        ):
            path = root / relative
            if path.exists():
                validate_skill_file(path, result, expected_version, require_all_compatibility=False)
    marker_files = [
        ".agents/skills/salesforce-agent-optimizer/SKILL.md",
        ".claude/skills/salesforce-agent-optimizer/SKILL.md",
        "AGENTS.md",
        ".github/copilot-instructions.md",
        ".github/instructions/salesforce-agent-optimizer.instructions.md",
    ]
    for relative in marker_files:
        path = root / relative
        if path.exists() and GENERATED_MARKER not in read_text(path):
            result.error(f"Generated marker missing from installed file: {relative}")
    validate_installed_yaml(root, result)
    validate_installed_text_shape(root, result)
    return result


def validate_installed_yaml(root: Path, result: ValidationResult) -> None:
    for relative in INSTALL_REQUIRED_FILES:
        path = root / relative
        if not path.exists() or path.suffix.lower() not in YAML_SUFFIXES:
            continue
        text = read_text(path)
        if yaml is not None:
            try:
                yaml.safe_load(text)
            except Exception as exc:  # noqa: BLE001
                result.error(f"Invalid YAML {relative}: {exc}")
        elif "\t" in text:
            result.error(f"Invalid YAML {relative}: tab indentation is not supported")


def validate_installed_text_shape(root: Path, result: ValidationResult) -> None:
    for relative in INSTALL_REQUIRED_FILES:
        path = root / relative
        if not path.exists() or path.suffix.lower() not in TEXT_SUFFIXES | YAML_SUFFIXES:
            continue
        data = path.read_bytes()
        try:
            text = data.decode("utf-8")
        except UnicodeDecodeError as exc:
            result.error(f"File is not UTF-8: {relative}: {exc}")
            continue
        if data and not data.endswith(b"\n"):
            result.error(f"Missing final newline: {relative}")
        if b"\r\n" in data:
            result.error(f"CRLF newline found; expected LF: {relative}")
        if len(text) > 300 and len(text.splitlines()) <= 1:
            result.error(f"File appears collapsed into one line: {relative}")


def validate_auto(root: Path, expected_version: str | None = None) -> ValidationResult:
    if (root / "SKILL.md").exists() and (root / "pyproject.toml").exists():
        return validate_source_tree(root)
    return validate_installation(root, expected_version=expected_version)
