#!/usr/bin/env python3
"""Synchronize agent instruction files from canonical skill sources."""

from __future__ import annotations

import argparse
import difflib
import json
from pathlib import Path

try:
    import yaml
except ImportError as exc:  # pragma: no cover - environment setup handles this
    raise SystemExit("PyYAML is required. Install with: python -m pip install PyYAML") from exc


ROOT = Path(__file__).resolve().parent.parent
SKILL_NAME = "salesforce-agent-optimizer"
GENERATED = "<!-- Generated by salesforce-agent-optimizer. Managed by sfao. -->"
GENERATED_NOTE = "Generated from references/agent-instruction-spine.md."
COPILOT_PREFIX = (
    "Copilot compliance gate: before inspecting metadata or editing files, show the current "
    "Salesforce Agent Optimizer phase, the references/Knowledge you will consult, whether "
    "implementation is required, and whether approval is needed. Do not skip directly to "
    "metadata parsing."
)
COPILOT_APPLY_TO = (
    "**/{force-app/**,src/**,*.cls,*.trigger,*.apex,*.js,*.html,*.css,*.xml,"
    "*.flow-meta.xml,*.object-meta.xml,*.field-meta.xml,sfdx-project.json,package.xml}"
)


def read_version(root: Path) -> str:
    return (root / "VERSION").read_text(encoding="utf-8").strip()


def read_spine(root: Path) -> str:
    return (root / "references" / "agent-instruction-spine.md").read_text(encoding="utf-8").strip()


def frontmatter(version: str, agent: str, description: str) -> str:
    payload = {
        "name": SKILL_NAME,
        "description": description,
        "license": "MIT",
        "compatibility": {
            "agents": [agent],
            "platforms": ["Windows", "macOS", "Linux"],
            "prerequisites": ["Python 3.10+", "Git", "Salesforce CLI"],
        },
        "metadata": {"version": version},
    }
    return "---\n" + yaml.safe_dump(payload, sort_keys=False).strip() + "\n---"


def managed_markdown(title: str, spine: str, prefix: str = "") -> str:
    parts = [GENERATED, GENERATED_NOTE, "", f"# {title}", ""]
    if prefix:
        parts.extend([prefix.strip(), ""])
    parts.append(spine.partition("\n\n")[2] or spine)
    return "\n".join(parts).rstrip() + "\n"


def shim_skill(version: str, agent: str, title: str, description: str, prefix: str, spine: str) -> str:
    return (
        frontmatter(version, agent, description)
        + "\n\n"
        + managed_markdown(title, spine, prefix=prefix)
    )


def generated_files(root: Path) -> dict[Path, str]:
    version = read_version(root)
    spine = read_spine(root)
    files: dict[Path, str] = {}

    files[root / "AGENTS.md"] = managed_markdown(
        "Salesforce Agent Optimizer",
        spine,
        "Universal instruction spine for Codex, Claude Code, GitHub Copilot, and compatible coding agents.",
    )
    files[root / "agents" / "claude-code.md"] = managed_markdown(
        "Salesforce Agent Optimizer For Claude Code",
        spine,
        "Use the local `salesforce-agent-optimizer` skill for Salesforce work. Keep `references/` and `scripts/` available.",
    )
    files[root / "agents" / "github-copilot-instructions.md"] = managed_markdown(
        "Salesforce Agent Optimizer For GitHub Copilot",
        spine,
        COPILOT_PREFIX,
    )
    files[root / ".github" / "copilot-instructions.md"] = managed_markdown(
        "Salesforce Agent Optimizer",
        spine,
        COPILOT_PREFIX,
    )
    files[root / ".github" / "instructions" / "salesforce-agent-optimizer.instructions.md"] = (
        "---\n"
        + yaml.safe_dump({"applyTo": COPILOT_APPLY_TO}, sort_keys=False).strip()
        + "\n---\n\n"
        + managed_markdown("Salesforce Agent Optimizer", spine, prefix=COPILOT_PREFIX)
    )
    files[root / ".agents" / "skills" / SKILL_NAME / "SKILL.md"] = shim_skill(
        version,
        "Codex",
        "Salesforce Agent Optimizer Repo Skill",
        "Repository-local Codex shim for Salesforce Agent Optimizer. Read the root SKILL.md and routed references.",
        "This is a repository-native Codex discovery shim. Read `../../../SKILL.md` as canonical.",
        spine,
    )
    files[root / ".claude" / "skills" / SKILL_NAME / "SKILL.md"] = shim_skill(
        version,
        "Claude Code",
        "Salesforce Agent Optimizer For Claude Code",
        "Claude Code shim for Salesforce Agent Optimizer. Read the root SKILL.md and routed references.",
        "This is a Claude Code discovery shim. Read `../../../SKILL.md` as canonical.",
        spine,
    )
    files[root / "agents" / "openai.yaml"] = yaml.safe_dump(
        {
            "interface": {
                "display_name": "Salesforce Agent Optimizer",
                "short_description": "Salesforce delivery with routed least-privilege and delete guardrails",
                "default_prompt": (
                    "Use $salesforce-agent-optimizer to route Salesforce work through minimal context, "
                    "mandatory request review, planning, approval, implementation decision, validation, "
                    "least-privilege org inspection, explicit delete approval, and package.xml generation."
                ),
            },
            "metadata": {"version": version},
        },
        sort_keys=False,
        width=120,
    )
    return files


def write_if_needed(path: Path, content: str, check: bool, diffs: list[str]) -> None:
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    if existing == content:
        return
    if check:
        diff = difflib.unified_diff(
            existing.splitlines(),
            content.splitlines(),
            fromfile=str(path),
            tofile=str(path) + " (generated)",
            lineterm="",
        )
        diffs.append("\n".join(diff))
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser(description="Synchronize generated agent instruction files.")
    parser.add_argument("--root", default=ROOT)
    parser.add_argument("--check", action="store_true", help="Fail if generated files are stale.")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    diffs: list[str] = []
    changed: list[str] = []
    for path, content in generated_files(root).items():
        before = path.read_text(encoding="utf-8") if path.exists() else ""
        write_if_needed(path, content, args.check, diffs)
        if before != content:
            changed.append(str(path.relative_to(root)))

    result = {"ok": not diffs, "changed": changed, "stale": bool(diffs)}
    if args.json:
        print(json.dumps(result, indent=2, sort_keys=True))
    elif diffs:
        print("\n\n".join(diffs))
    elif changed and not args.check:
        print("Synchronized agent instruction files:")
        for item in changed:
            print(f"- {item}")
    else:
        print("Agent instruction files are up to date.")
    return 1 if diffs else 0


if __name__ == "__main__":
    raise SystemExit(main())
